[workspace]
members = [
	"typify",
	"typify-impl",
	"typify-macro",
	"typify-test",
	"example-build",
	"example-macro",
]
default-members = [
	"typify",
	"typify-impl",
	"typify-macro",
	"typify-test",
]

[workspace.dependencies]
proc-macro2 = "1.0"
quote = "1.0"
regress = "0.4.1"
schemars = "0.8.10"
serde = "1.0"
serde_json = "1.0"
syn = "1.0"
typify = { path = "typify" }
