[package]
name = "example-build"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
serde = { workspace = true }

[build-dependencies]
schemars = { workspace = true }
serde_json = { workspace = true }
typify = { path = "../typify" }
