[package]
name = "typify-macro"
version = "0.0.11-dev"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com"]
edition = "2021"
license = "Apache-2.0"
description = "typify macro implementation"
repository = "https://github.com/oxidecomputer/typify"
readme = "../README.md"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_tokenstream = "0.1.3"
syn = { workspace = true }
typify-impl = { version = "0.0.11-dev", path = "../typify-impl" }

[lib]
proc-macro = true
