[package]
name = "typify-impl"
version = "0.0.11-dev"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com"]
edition = "2021"
license = "Apache-2.0"
description = "typify backend implementation"
repository = "https://github.com/oxidecomputer/typify"
readme = "../README.md"

[dependencies]
heck = "0.4.0"
log = "0.4"
proc-macro2 = { workspace = true }
quote = { workspace = true }
regress = { workspace = true }
rustfmt-wrapper = "0.2"
schemars = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true, features = ["full"] }
thiserror = "1.0"
unicode-ident = "1.0.3"

[dev-dependencies]
expectorate = "1.0"
paste = "1.0"
schema = "0.0.1"
schemars = { workspace = true, features = ["uuid1"] }
serde = { workspace = true }
uuid = "1.1.2"
