[package]
name = "typify-test"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
regress = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
ipnetwork = { version = "0.20.0", features = ["schemars"] }
schemars = { workspace = true }
serde = { workspace = true }
typify = { path = "../typify" }
