[package]
name = "example-macro"
version = "0.0.0"
authors = ["Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2021"

[dependencies]
typify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
